import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :kiroku, KirokuWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# SSL redirect and HSTS are handled by the reverse proxy (Caddy/Nginx) in
# production, not by the application. This allows direct HTTP access during
# initial setup (e.g., via IP address before the domain and TLS are configured).
# The reverse proxy should:
#   1. Terminate TLS and forward to the app on port 4000
#   2. Set X-Forwarded-Proto: https so the app knows the original scheme
#   3. Handle HTTP → HTTPS redirects and HSTS headers

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
