defmodule Kiroku.Repo.Migrations.CreateRepositorySchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:view_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :resource_type, :text, null: false
      add :resource_id, :uuid, null: false
      add :ip_hash, :text
      add :user_agent, :text
      add :referrer, :text
      add :country_code, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "view_events_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:view_events, [:inserted_at])

    create index(:view_events, [:resource_type, :resource_id])

    alter table(:users) do
      add :full_name, :text
      add :external_id, :text
      add :user_type, :text, default: "member"
      add :active, :boolean, default: true
    end

    create table(:rbac_policies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :resource_type, :text, null: false
      add :resource_id, :uuid, null: false
      add :group_id, :uuid
      add :user_id, :uuid
      add :action, :text, null: false
      add :start_date, :naive_datetime
      add :end_date, :naive_datetime
      add :policy_type, :text, default: "custom"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:rbac_policies, [:user_id])

    create index(:rbac_policies, [:group_id])

    create index(:rbac_policies, [:resource_type, :resource_id])

    create table(:items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :handle, :text
      add :legacy_id, :text
      add :idpustaka, :text
      add :title, :text, null: false
      add :title_raw, :text
      add :title_alt, :text
      add :abstract, :text
      add :abstract_raw, :text
      add :abstract_alt, :text
      add :language, :text, default: "id"
      add :item_type, :text, default: "skripsi"
      add :degree_level, :text
      add :department, :text
      add :faculty, :text
      add :program_study, :text
      add :institution, :text
      add :student_id, :text
      add :student_name, :text
      add :status, :text, default: "draft"
      add :access_level, :text, default: "open"
      add :discoverable, :boolean, default: true
      add :withdrawn, :boolean, default: false
      add :date_submitted, :date
      add :date_issued, :date
      add :date_available, :date
      add :publication_year, :bigint
      add :published_at, :naive_datetime
      add :embargo_open_date, :date
      add :embargo_close_date, :date
      add :embargo_reason, :text
      add :base_url, :text
      add :approval_date, :date
      add :research_location, :text
      add :research_period, :text
      add :funding_source, :text
      add :thesis_type_detail, :text
      add :subject_classification, :text
      add :originality_statement, :boolean, default: false
      add :legal_subject_matter, :text
      add :case_reference, :text
      add :court_level, :text
      add :legal_issue, :text
      add :jurisdiction, :text
      add :legal_analysis_method, :text
      add :case_study_type, :text
      add :case_subject, :text
      add :case_period, :text
      add :case_location, :text
      add :analysis_framework, :text
      add :subject_anonymized, :boolean, default: false
      add :informed_consent, :boolean, default: false
      add :ethics_approval_number, :text
      add :industry_partner, :text
      add :data_collection_method, :text
      add :project_title, :text
      add :project_type, :text
      add :project_client, :text
      add :project_period, :text
      add :project_location, :text
      add :project_deliverable, :text
      add :team_role, :text
      add :project_budget, :text
      add :patent_pending, :boolean, default: false
      add :creative_work_type, :text
      add :medium_material, :text
      add :dimensions_duration, :text
      add :creation_period, :text
      add :artistic_statement, :text
      add :exhibition_performance, :text
      add :exhibition_date, :date
      add :exhibition_venue, :text
      add :copyright_type, :text
      add :collection_owner, :text
      add :technology_type, :text
      add :problem_solved, :text
      add :target_user, :text
      add :implementation_status, :text
      add :testing_method, :text
      add :license_type, :text
      add :patent_status, :text
      add :hki_number, :text
      add :industry_tested_at, :text
      add :journal_name, :text
      add :sinta_id, :text
      add :sinta_accreditation, :text
      add :issn_print, :text
      add :issn_online, :text
      add :volume, :text
      add :issue, :text
      add :page_start, :bigint
      add :page_end, :bigint
      add :doi, :text
      add :publisher, :text
      add :corresponding_author, :text
      add :garuda_id, :text
      add :crossref_registered, :boolean, default: false
      add :peer_review_type, :text
      add :submission_date, :date
      add :acceptance_date, :date
      add :article_type, :text
      add :scopus_id, :text
      add :wos_id, :text
      add :sjr_score, :decimal
      add :impact_factor, :decimal
      add :quartile, :text
      add :subject_area, :text
      add :indexed_in, :text
      add :altmetric_score, :bigint
      add :special_issue, :text
      add :conference_origin, :text
      add :open_access_apc, :text
      add :conference_name, :text
      add :conference_acronym, :text
      add :conference_date, :date
      add :conference_location, :text
      add :conference_type, :text
      add :proceeding_publisher, :text
      add :proceeding_series, :text
      add :isbn_proceeding, :text
      add :issn_proceeding, :text
      add :presentation_type, :text
      add :acceptance_rate, :text
      add :presentation_date, :date
      add :session_name, :text
      add :best_paper_award, :text
      add :capstone_theme, :text
      add :team_lead, :text
      add :partner_institution, :text
      add :problem_statement, :text
      add :solution_description, :text
      add :impact_target, :text
      add :duration_semester, :text
      add :mbkm_scheme, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :collection_id, :uuid, null: false
      add :submitter_id, :uuid
    end

    create index(:items, [:faculty])

    create index(:items, [:department])

    create index(:items, [:discoverable])

    create index(:items, [:publication_year])

    create index(:items, [:status])

    create index(:items, [:student_id])

    create table(:item_team_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :member_name, :text, null: false
      add :member_nim, :text
      add :program_study, :text
      add :role, :text
      add :sequence, :bigint, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:items,
            column: :id,
            name: "item_team_members_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:item_metadata, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :field_schema, :text, null: false
      add :field_element, :text, null: false
      add :field_qualifier, :text
      add :field_value, :text, null: false
      add :language, :text
      add :confidence, :bigint, default: 0
      add :place, :bigint, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:items,
            column: :id,
            name: "item_metadata_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:item_metadata, [:field_schema, :field_element])

    create table(:item_keywords, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :keyword, :text, null: false
      add :language, :text, default: "id"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:items,
            column: :id,
            name: "item_keywords_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:item_keywords, [:item_id])

    create index(:item_keywords, [:keyword])

    create table(:item_examiners, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :examiner_name, :text, null: false
      add :examiner_nip, :text
      add :sequence, :bigint, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:items,
            column: :id,
            name: "item_examiners_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:item_authors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :author_name, :text, null: false
      add :author_email, :text
      add :author_affiliation, :text
      add :orcid_id, :text
      add :sequence, :bigint, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:items,
            column: :id,
            name: "item_authors_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:item_advisors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :advisor_name, :text, null: false
      add :advisor_role, :text, default: "main_advisor"
      add :advisor_nip, :text
      add :sequence, :bigint, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:items,
            column: :id,
            name: "item_advisors_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :is_system, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:groups, [:name], name: "groups_unique_name_index")

    create table(:group_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :expires_at, :naive_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "group_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_memberships_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:group_memberships, [:user_id, :group_id],
             name: "group_memberships_unique_user_group_index"
           )

    create table(:communities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :handle, :text
      add :short_description, :text
      add :description, :text
      add :logo_bitstream_id, :uuid
      add :position, :bigint, default: 0
      add :is_active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parent_community_id,
          references(:communities,
            column: :id,
            name: "communities_parent_community_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:communities, [:handle], name: "communities_unique_handle_index")

    create table(:collections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:items) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "items_collection_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :submitter_id,
             references(:users,
               column: :id,
               name: "items_submitter_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:items, [:handle], name: "items_unique_handle_index")

    alter table(:collections) do
      add :name, :text, null: false
      add :handle, :text
      add :short_description, :text
      add :description, :text
      add :logo_bitstream_id, :uuid
      add :license_text, :text
      add :position, :bigint, default: 0
      add :is_active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :community_id,
          references(:communities,
            column: :id,
            name: "collections_community_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:collections, [:handle], name: "collections_unique_handle_index")

    create table(:bitstreams, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :filename, :text, null: false
      add :bundle_name, :text, default: "ORIGINAL"
      add :sequence, :bigint, default: 0
      add :description, :text
      add :storage_type, :text, default: "url"
      add :storage_url, :text
      add :storage_path, :text
      add :storage_bucket, :text
      add :mime_type, :text
      add :size_bytes, :bigint, default: 0
      add :checksum, :text
      add :checksum_algorithm, :text, default: "md5"
      add :access_level, :text, default: "inherit"
      add :embargo_open_date, :date
      add :embargo_close_date, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:items,
            column: :id,
            name: "bitstreams_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:bitstreams, [:item_id])

    create index(:bitstreams, [:bundle_name])
  end

  def down do
    drop constraint(:bitstreams, "bitstreams_item_id_fkey")

    drop_if_exists index(:bitstreams, [:bundle_name])

    drop_if_exists index(:bitstreams, [:item_id])

    drop table(:bitstreams)

    drop_if_exists unique_index(:collections, [:handle], name: "collections_unique_handle_index")

    drop constraint(:collections, "collections_community_id_fkey")

    alter table(:collections) do
      remove :community_id
      remove :updated_at
      remove :inserted_at
      remove :is_active
      remove :position
      remove :license_text
      remove :logo_bitstream_id
      remove :description
      remove :short_description
      remove :handle
      remove :name
    end

    drop_if_exists unique_index(:items, [:handle], name: "items_unique_handle_index")

    drop constraint(:items, "items_collection_id_fkey")

    drop constraint(:items, "items_submitter_id_fkey")

    alter table(:items) do
      modify :submitter_id, :uuid
      modify :collection_id, :uuid
    end

    drop table(:collections)

    drop_if_exists unique_index(:communities, [:handle], name: "communities_unique_handle_index")

    drop constraint(:communities, "communities_parent_community_id_fkey")

    drop table(:communities)

    drop_if_exists unique_index(:group_memberships, [:user_id, :group_id],
                     name: "group_memberships_unique_user_group_index"
                   )

    drop constraint(:group_memberships, "group_memberships_user_id_fkey")

    drop constraint(:group_memberships, "group_memberships_group_id_fkey")

    drop table(:group_memberships)

    drop_if_exists unique_index(:groups, [:name], name: "groups_unique_name_index")

    drop table(:groups)

    drop constraint(:item_advisors, "item_advisors_item_id_fkey")

    drop table(:item_advisors)

    drop constraint(:item_authors, "item_authors_item_id_fkey")

    drop table(:item_authors)

    drop constraint(:item_examiners, "item_examiners_item_id_fkey")

    drop table(:item_examiners)

    drop constraint(:item_keywords, "item_keywords_item_id_fkey")

    drop_if_exists index(:item_keywords, [:keyword])

    drop_if_exists index(:item_keywords, [:item_id])

    drop table(:item_keywords)

    drop constraint(:item_metadata, "item_metadata_item_id_fkey")

    drop_if_exists index(:item_metadata, [:field_schema, :field_element])

    drop table(:item_metadata)

    drop constraint(:item_team_members, "item_team_members_item_id_fkey")

    drop table(:item_team_members)

    drop_if_exists index(:items, [:student_id])

    drop_if_exists index(:items, [:status])

    drop_if_exists index(:items, [:publication_year])

    drop_if_exists index(:items, [:discoverable])

    drop_if_exists index(:items, [:department])

    drop_if_exists index(:items, [:faculty])

    drop table(:items)

    drop_if_exists index(:rbac_policies, [:resource_type, :resource_id])

    drop_if_exists index(:rbac_policies, [:group_id])

    drop_if_exists index(:rbac_policies, [:user_id])

    drop table(:rbac_policies)

    alter table(:users) do
      remove :active
      remove :user_type
      remove :external_id
      remove :full_name
    end

    drop constraint(:view_events, "view_events_user_id_fkey")

    drop_if_exists index(:view_events, [:resource_type, :resource_id])

    drop_if_exists index(:view_events, [:inserted_at])

    drop table(:view_events)
  end
end
